language: python
python:
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker network create proxy
  
install:
  - docker-compose -f "docker-compose.yml" up

script:
  - docker-compose run --rm --no-deps  web odoo --test-enable --stop-after-init --workers 0 -u hr 