export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';

export const GET_DETAILS_PRODUCT = 'GET_DETAILS_PRODUCT';