version: '3.5'

services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - reverse-proxy-net
      - db-net
    labels:
      - "traefik.enable=false"

networks:
  reverse-proxy-net:
    external: true
  db-net:
    name: db-net
    driver: overlay