version: '3.5'

services:
  traefik:
    image: traefik:1.7
    command:
      - --docker
      - --docker.swarmMode
      - --docker.exposedByDefault=false
      - --docker.watch
      - --docker.domain=traefik.lc
    ports:
      - 80:80
    networks:
      - reverse-proxy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role==manager
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy-net"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.lc"

networks:
 reverse-proxy-net:
   name: reverse-proxy-net
   driver: overlay