version: '3.5'

services:
  web-app:
    image: containous/whoami:latest
    networks:
      - reverse-proxy-net
      - web-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy-net"
    deploy:
      replicas: 4

networks:
  reverse-proxy-net:
    external: true
  web-net:
    name: web-net
    driver: overlay